
import java.util.ArrayList;

public class Resultado_PC extends javax.swing.JFrame {

    public int racha=0;
    public int num_partida=0;
    public String usuario="";
    public int jugada_pc=0;
    public int jugada_usuario=0;
    public String final_partida="";
    public String direc_logros="";
    public String direc_historial="";
    public Resultado_PC() {
        initComponents();
    }

    public void setRacha(int racha) {
        this.racha = racha;
    }

    public void setNum_partida(int num_partida) {
        this.num_partida = num_partida;
    }

    public void setJugada_PC(int jugada){
        jugada_pc=jugada;
    }
    
    public void setJugada_Usuario(int jugada){
        jugada_usuario=jugada;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public void setFinal_Partida(String final_partida) {
        this.final_partida = final_partida;
    }

    public void setDirec_Logros(String direc_logros) {
        this.direc_logros = direc_logros;
    }

    public void setDirec_Historial(String direc_historial) {
        this.direc_historial = direc_historial;
    }

    public void cargar_datos(){
        lbl_usuario.setText(usuario+": "+Nom_Jugada(jugada_usuario));
        lbl_pc.setText("Computadora: "+Nom_Jugada(jugada_pc));
        lbl_resultado.setText(final_partida);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_logro_aviso = new javax.swing.JLabel();
        lbl_logro_obtenido = new javax.swing.JLabel();
        lbl_resultado = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        lbl_pc = new javax.swing.JLabel();
        BT_volver_a_jugar = new javax.swing.JButton();
        BT_Terminar_juego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_logro_aviso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_logro_aviso.setText(" ");

        lbl_logro_obtenido.setText(" ");

        lbl_resultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_resultado.setText("Resultado");

        lbl_usuario.setText("usuario");

        lbl_pc.setText("pc");

        BT_volver_a_jugar.setText("Volver a jugar");
        BT_volver_a_jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_volver_a_jugarActionPerformed(evt);
            }
        });

        BT_Terminar_juego.setText("Terminar Juego");
        BT_Terminar_juego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_Terminar_juegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BT_volver_a_jugar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_pc)
                        .addComponent(lbl_usuario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(BT_Terminar_juego)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_logro_aviso)
                            .addComponent(lbl_logro_obtenido)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(lbl_resultado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_logro_aviso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_logro_obtenido)
                .addGap(35, 35, 35)
                .addComponent(lbl_resultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_pc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_volver_a_jugar)
                    .addComponent(BT_Terminar_juego))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_Terminar_juegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_Terminar_juegoActionPerformed
        Menu newframe=new Menu();
        newframe.setDirec_Historial(direc_historial);
        newframe.setDirec_Logros(direc_logros);
        newframe.setUsuario(usuario);
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BT_Terminar_juegoActionPerformed

    private void BT_volver_a_jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_volver_a_jugarActionPerformed
        Juego_PC newframe=new Juego_PC();
        newframe.setUsuario(usuario);
        newframe.setDirec_Historial(direc_historial);
        newframe.setDirec_Logros(direc_logros);
        newframe.setNum_partida(num_partida);
        newframe.setRacha(racha);
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BT_volver_a_jugarActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultado_PC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Terminar_juego;
    private javax.swing.JButton BT_volver_a_jugar;
    private javax.swing.JLabel lbl_logro_aviso;
    private javax.swing.JLabel lbl_logro_obtenido;
    private static javax.swing.JLabel lbl_pc;
    private static javax.swing.JLabel lbl_resultado;
    private static javax.swing.JLabel lbl_usuario;
    // End of variables declaration//GEN-END:variables
    private String Nom_Jugada(int jugada) {
        if(jugada==1)
            return "Piedra";
        if(jugada==2)
            return "Papel";

        return "Tijeras";
    }

    public void obtener_logro(ArrayList<Logro> lista, int racha, int partida) {
        String logros_obtenidos=" ";
        Logro act=new Logro();
        for (int aux = 0; aux < lista.size(); aux++) {
            act = lista.get(aux);
            if (!act.getEstado()) {
                act.setEstado(racha, partida);
                if (act.getEstado()) {
                    lbl_logro_aviso.setText("¡LOGRO OBTENIDO!");
                    if(logros_obtenidos.equals(" ")){
                        logros_obtenidos="-"+act.getNombre();
                    }else{
                        logros_obtenidos=logros_obtenidos+"<p>-"+act.getNombre();
                    }
                    lista.set(aux, act);
                }
            }
        }
        lbl_logro_obtenido.setText("<html>"+logros_obtenidos+"<html>");
        act.guardarLogros(lista, direc_logros);
    }
}
